#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sms")]
	public partial class myDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertrole(role instance);
    partial void Updaterole(role instance);
    partial void Deleterole(role instance);
    partial void Insertstaff(staff instance);
    partial void Updatestaff(staff instance);
    partial void Deletestaff(staff instance);
    partial void Insertsection(section instance);
    partial void Updatesection(section instance);
    partial void Deletesection(section instance);
    partial void Insertsubject(subject instance);
    partial void Updatesubject(subject instance);
    partial void Deletesubject(subject instance);
    partial void Inserthousse(housse instance);
    partial void Updatehousse(housse instance);
    partial void Deletehousse(housse instance);
    partial void Insertshift(shift instance);
    partial void Updateshift(shift instance);
    partial void Deleteshift(shift instance);
    partial void Insertlevel(level instance);
    partial void Updatelevel(level instance);
    partial void Deletelevel(level instance);
    partial void Insertclass(clase instance);
    partial void Updateclass(clase instance);
    partial void Deleteclass(clase instance);
    partial void Inserttiming(timing instance);
    partial void Updatetiming(timing instance);
    partial void Deletetiming(timing instance);
    #endregion
		
		public myDBDataContext() : 
				base(global::SchoolManagementSystem.Properties.Settings.Default.smsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public myDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<role> roles
		{
			get
			{
				return this.GetTable<role>();
			}
		}
		
		public System.Data.Linq.Table<staff> staffs
		{
			get
			{
				return this.GetTable<staff>();
			}
		}
		
		public System.Data.Linq.Table<section> sections
		{
			get
			{
				return this.GetTable<section>();
			}
		}
		
		public System.Data.Linq.Table<subject> subjects
		{
			get
			{
				return this.GetTable<subject>();
			}
		}
		
		public System.Data.Linq.Table<housse> housses
		{
			get
			{
				return this.GetTable<housse>();
			}
		}
		
		public System.Data.Linq.Table<shift> shifts
		{
			get
			{
				return this.GetTable<shift>();
			}
		}
		
		public System.Data.Linq.Table<level> levels
		{
			get
			{
				return this.GetTable<level>();
			}
		}

        public System.Data.Linq.Table<clase> classes
		{
			get
			{
                return this.GetTable<clase>();
			}
		}
		
		public System.Data.Linq.Table<timing> timings
		{
			get
			{
				return this.GetTable<timing>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertRoles")]
		public int st_insertRoles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getRoles")]
		public ISingleResult<st_getRolesResult> st_getRoles()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getRolesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateRoles")]
		public int st_updateRoles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, status, roleID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deleteRole")]
		public int st_deleteRole([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_searchRoles")]
		public ISingleResult<st_searchRolesResult> st_searchRoles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string data)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), data);
			return ((ISingleResult<st_searchRolesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertStaff")]
		public int st_insertStaff([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string phone1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string phone2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> role, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary image)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, username, password, phone1, phone2, role, status, image);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertStaffWithoutImage")]
		public int st_insertStaffWithoutImage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string phone1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string phone2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> role, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, username, password, phone1, phone2, role, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateStaffWithoutImage")]
		public int st_updateStaffWithoutImage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string phone1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string phone2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> role, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> staffID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, username, password, phone1, phone2, role, status, staffID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateStaff")]
		public int st_updateStaff([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string phone1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string phone2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> role, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary image, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> staffID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, username, password, phone1, phone2, role, status, image, staffID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deleteStaff")]
		public int st_deleteStaff([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> staffID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), staffID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getStaffDetails")]
		public ISingleResult<st_getStaffDetailsResult> st_getStaffDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getStaffDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertSections")]
		public int st_insertSections([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateSections")]
		public int st_updateSections([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> secID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, status, secID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deleteSection")]
		public int st_deleteSection([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> secID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), secID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getSections")]
		public ISingleResult<st_getSectionsResult> st_getSections()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getSectionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertClass")]
		public int st_insertClass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateClass")]
		public int st_updateClass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> clsID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, status, clsID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deleteClass")]
		public int st_deleteClass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> clsID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clsID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertSubject")]
		public int st_insertSubject([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> classID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, classID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateSubject")]
		public int st_updateSubject([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> classID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, classID, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deleteSubject")]
		public int st_deleteSubject([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getSubjects")]
		public ISingleResult<st_getSubjectsResult> st_getSubjects()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getSubjectsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateShifts")]
		public int st_updateShifts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> to, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> shiftID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, number, from, to, shiftID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertShifts")]
		public int st_insertShifts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> to)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, number, from, to);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deleteShifts")]
		public int st_deleteShifts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> shiftID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), shiftID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getShifts")]
		public ISingleResult<st_getShiftsResult> st_getShifts()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getShiftsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_gethousse")]
		public ISingleResult<st_gethousseResult> st_gethousse()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_gethousseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_inserthousse")]
		public int st_inserthousse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updatehouses")]
		public int st_updatehouses([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, status, hID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deletehouses")]
		public int st_deletehouses([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getStaffLoginDetails")]
		public ISingleResult<st_getStaffLoginDetailsResult> st_getStaffLoginDetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((ISingleResult<st_getStaffLoginDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deleteTimings")]
		public int st_deleteTimings([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getlevel")]
		public ISingleResult<st_getlevelResult> st_getlevel()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getlevelResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertlevel")]
		public int st_insertlevel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string lvlname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lvlname);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updatelevel")]
		public int st_updatelevel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string lvlname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, lvlname);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deletelevel")]
		public int st_deletelevel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getClasses")]
		public ISingleResult<st_getClassesResult> st_getClasses()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getClassesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getTimings")]
		public ISingleResult<st_getTimingsResult> st_getTimings()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getTimingsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertTimings")]
		public int st_insertTimings([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> shift, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> to, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string day, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> levelID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, shift, from, to, day, levelID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateTimings")]
		public int st_updateTimings([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> shift, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> to, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string day, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> levelID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, shift, from, to, day, tID, levelID);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.roles")]
	public partial class role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _r_id;
		
		private string _r_name;
		
		private byte _r_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onr_idChanging(int value);
    partial void Onr_idChanged();
    partial void Onr_nameChanging(string value);
    partial void Onr_nameChanged();
    partial void Onr_statusChanging(byte value);
    partial void Onr_statusChanged();
    #endregion
		
		public role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int r_id
		{
			get
			{
				return this._r_id;
			}
			set
			{
				if ((this._r_id != value))
				{
					this.Onr_idChanging(value);
					this.SendPropertyChanging();
					this._r_id = value;
					this.SendPropertyChanged("r_id");
					this.Onr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string r_name
		{
			get
			{
				return this._r_name;
			}
			set
			{
				if ((this._r_name != value))
				{
					this.Onr_nameChanging(value);
					this.SendPropertyChanging();
					this._r_name = value;
					this.SendPropertyChanged("r_name");
					this.Onr_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_status", DbType="TinyInt NOT NULL")]
		public byte r_status
		{
			get
			{
				return this._r_status;
			}
			set
			{
				if ((this._r_status != value))
				{
					this.Onr_statusChanging(value);
					this.SendPropertyChanging();
					this._r_status = value;
					this.SendPropertyChanged("r_status");
					this.Onr_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.staff")]
	public partial class staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _st_id;
		
		private string _st_name;
		
		private string _st_username;
		
		private string _st_password;
		
		private string _st_phone1;
		
		private string _st_phone2;
		
		private int _st_role;
		
		private byte _st_status;
		
		private System.Data.Linq.Binary _st_image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onst_idChanging(int value);
    partial void Onst_idChanged();
    partial void Onst_nameChanging(string value);
    partial void Onst_nameChanged();
    partial void Onst_usernameChanging(string value);
    partial void Onst_usernameChanged();
    partial void Onst_passwordChanging(string value);
    partial void Onst_passwordChanged();
    partial void Onst_phone1Changing(string value);
    partial void Onst_phone1Changed();
    partial void Onst_phone2Changing(string value);
    partial void Onst_phone2Changed();
    partial void Onst_roleChanging(int value);
    partial void Onst_roleChanged();
    partial void Onst_statusChanging(byte value);
    partial void Onst_statusChanged();
    partial void Onst_imageChanging(System.Data.Linq.Binary value);
    partial void Onst_imageChanged();
    #endregion
		
		public staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int st_id
		{
			get
			{
				return this._st_id;
			}
			set
			{
				if ((this._st_id != value))
				{
					this.Onst_idChanging(value);
					this.SendPropertyChanging();
					this._st_id = value;
					this.SendPropertyChanged("st_id");
					this.Onst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string st_name
		{
			get
			{
				return this._st_name;
			}
			set
			{
				if ((this._st_name != value))
				{
					this.Onst_nameChanging(value);
					this.SendPropertyChanging();
					this._st_name = value;
					this.SendPropertyChanged("st_name");
					this.Onst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_username", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string st_username
		{
			get
			{
				return this._st_username;
			}
			set
			{
				if ((this._st_username != value))
				{
					this.Onst_usernameChanging(value);
					this.SendPropertyChanging();
					this._st_username = value;
					this.SendPropertyChanged("st_username");
					this.Onst_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_password", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string st_password
		{
			get
			{
				return this._st_password;
			}
			set
			{
				if ((this._st_password != value))
				{
					this.Onst_passwordChanging(value);
					this.SendPropertyChanging();
					this._st_password = value;
					this.SendPropertyChanged("st_password");
					this.Onst_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_phone1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string st_phone1
		{
			get
			{
				return this._st_phone1;
			}
			set
			{
				if ((this._st_phone1 != value))
				{
					this.Onst_phone1Changing(value);
					this.SendPropertyChanging();
					this._st_phone1 = value;
					this.SendPropertyChanged("st_phone1");
					this.Onst_phone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_phone2", DbType="VarChar(15)")]
		public string st_phone2
		{
			get
			{
				return this._st_phone2;
			}
			set
			{
				if ((this._st_phone2 != value))
				{
					this.Onst_phone2Changing(value);
					this.SendPropertyChanging();
					this._st_phone2 = value;
					this.SendPropertyChanged("st_phone2");
					this.Onst_phone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_role", DbType="Int NOT NULL")]
		public int st_role
		{
			get
			{
				return this._st_role;
			}
			set
			{
				if ((this._st_role != value))
				{
					this.Onst_roleChanging(value);
					this.SendPropertyChanging();
					this._st_role = value;
					this.SendPropertyChanged("st_role");
					this.Onst_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_status", DbType="TinyInt NOT NULL")]
		public byte st_status
		{
			get
			{
				return this._st_status;
			}
			set
			{
				if ((this._st_status != value))
				{
					this.Onst_statusChanging(value);
					this.SendPropertyChanging();
					this._st_status = value;
					this.SendPropertyChanged("st_status");
					this.Onst_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary st_image
		{
			get
			{
				return this._st_image;
			}
			set
			{
				if ((this._st_image != value))
				{
					this.Onst_imageChanging(value);
					this.SendPropertyChanging();
					this._st_image = value;
					this.SendPropertyChanged("st_image");
					this.Onst_imageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sections")]
	public partial class section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sec_id;
		
		private string _sec_name;
		
		private byte _sec_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsec_idChanging(int value);
    partial void Onsec_idChanged();
    partial void Onsec_nameChanging(string value);
    partial void Onsec_nameChanged();
    partial void Onsec_statusChanging(byte value);
    partial void Onsec_statusChanged();
    #endregion
		
		public section()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sec_id
		{
			get
			{
				return this._sec_id;
			}
			set
			{
				if ((this._sec_id != value))
				{
					this.Onsec_idChanging(value);
					this.SendPropertyChanging();
					this._sec_id = value;
					this.SendPropertyChanged("sec_id");
					this.Onsec_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string sec_name
		{
			get
			{
				return this._sec_name;
			}
			set
			{
				if ((this._sec_name != value))
				{
					this.Onsec_nameChanging(value);
					this.SendPropertyChanging();
					this._sec_name = value;
					this.SendPropertyChanged("sec_name");
					this.Onsec_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_status", DbType="TinyInt NOT NULL")]
		public byte sec_status
		{
			get
			{
				return this._sec_status;
			}
			set
			{
				if ((this._sec_status != value))
				{
					this.Onsec_statusChanging(value);
					this.SendPropertyChanging();
					this._sec_status = value;
					this.SendPropertyChanged("sec_status");
					this.Onsec_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subjects")]
	public partial class subject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sub_id;
		
		private string _sub_name;
		
		private System.Nullable<int> _sub_classID;

        private EntityRef<clase> _class;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsub_idChanging(int value);
    partial void Onsub_idChanged();
    partial void Onsub_nameChanging(string value);
    partial void Onsub_nameChanged();
    partial void Onsub_classIDChanging(System.Nullable<int> value);
    partial void Onsub_classIDChanged();
    #endregion
		
		public subject()
		{
            this._class = default(EntityRef<clase>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sub_id
		{
			get
			{
				return this._sub_id;
			}
			set
			{
				if ((this._sub_id != value))
				{
					this.Onsub_idChanging(value);
					this.SendPropertyChanging();
					this._sub_id = value;
					this.SendPropertyChanged("sub_id");
					this.Onsub_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sub_name
		{
			get
			{
				return this._sub_name;
			}
			set
			{
				if ((this._sub_name != value))
				{
					this.Onsub_nameChanging(value);
					this.SendPropertyChanging();
					this._sub_name = value;
					this.SendPropertyChanged("sub_name");
					this.Onsub_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_classID", DbType="Int")]
		public System.Nullable<int> sub_classID
		{
			get
			{
				return this._sub_classID;
			}
			set
			{
				if ((this._sub_classID != value))
				{
					if (this._class.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsub_classIDChanging(value);
					this.SendPropertyChanging();
					this._sub_classID = value;
					this.SendPropertyChanged("sub_classID");
					this.Onsub_classIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="class_subject", Storage="_class", ThisKey="sub_classID", OtherKey="cls_id", IsForeignKey=true, DeleteRule="CASCADE")]
        public clase @class
		{
			get
			{
				return this._class.Entity;
			}
			set
			{
                clase previousValue = this._class.Entity;
				if (((previousValue != value) 
							|| (this._class.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._class.Entity = null;
						previousValue.subjects.Remove(this);
					}
					this._class.Entity = value;
					if ((value != null))
					{
						value.subjects.Add(this);
						this._sub_classID = value.cls_id;
					}
					else
					{
						this._sub_classID = default(Nullable<int>);
					}
					this.SendPropertyChanged("@class");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.housse")]
	public partial class housse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _h_id;
		
		private string _h_name;
		
		private byte _h_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onh_idChanging(int value);
    partial void Onh_idChanged();
    partial void Onh_nameChanging(string value);
    partial void Onh_nameChanged();
    partial void Onh_statusChanging(byte value);
    partial void Onh_statusChanged();
    #endregion
		
		public housse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int h_id
		{
			get
			{
				return this._h_id;
			}
			set
			{
				if ((this._h_id != value))
				{
					this.Onh_idChanging(value);
					this.SendPropertyChanging();
					this._h_id = value;
					this.SendPropertyChanged("h_id");
					this.Onh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string h_name
		{
			get
			{
				return this._h_name;
			}
			set
			{
				if ((this._h_name != value))
				{
					this.Onh_nameChanging(value);
					this.SendPropertyChanging();
					this._h_name = value;
					this.SendPropertyChanged("h_name");
					this.Onh_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_status", DbType="TinyInt NOT NULL")]
		public byte h_status
		{
			get
			{
				return this._h_status;
			}
			set
			{
				if ((this._h_status != value))
				{
					this.Onh_statusChanging(value);
					this.SendPropertyChanging();
					this._h_status = value;
					this.SendPropertyChanged("h_status");
					this.Onh_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.shifts")]
	public partial class shift : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sh_id;
		
		private string _sh_name;
		
		private byte _sh_number;
		
		private System.TimeSpan _sh_from;
		
		private System.TimeSpan _sh_to;
		
		private EntitySet<timing> _timings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsh_idChanging(int value);
    partial void Onsh_idChanged();
    partial void Onsh_nameChanging(string value);
    partial void Onsh_nameChanged();
    partial void Onsh_numberChanging(byte value);
    partial void Onsh_numberChanged();
    partial void Onsh_fromChanging(System.TimeSpan value);
    partial void Onsh_fromChanged();
    partial void Onsh_toChanging(System.TimeSpan value);
    partial void Onsh_toChanged();
    #endregion
		
		public shift()
		{
			this._timings = new EntitySet<timing>(new Action<timing>(this.attach_timings), new Action<timing>(this.detach_timings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sh_id
		{
			get
			{
				return this._sh_id;
			}
			set
			{
				if ((this._sh_id != value))
				{
					this.Onsh_idChanging(value);
					this.SendPropertyChanging();
					this._sh_id = value;
					this.SendPropertyChanged("sh_id");
					this.Onsh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sh_name
		{
			get
			{
				return this._sh_name;
			}
			set
			{
				if ((this._sh_name != value))
				{
					this.Onsh_nameChanging(value);
					this.SendPropertyChanging();
					this._sh_name = value;
					this.SendPropertyChanged("sh_name");
					this.Onsh_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh_number", DbType="TinyInt NOT NULL")]
		public byte sh_number
		{
			get
			{
				return this._sh_number;
			}
			set
			{
				if ((this._sh_number != value))
				{
					this.Onsh_numberChanging(value);
					this.SendPropertyChanging();
					this._sh_number = value;
					this.SendPropertyChanged("sh_number");
					this.Onsh_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh_from", DbType="Time NOT NULL")]
		public System.TimeSpan sh_from
		{
			get
			{
				return this._sh_from;
			}
			set
			{
				if ((this._sh_from != value))
				{
					this.Onsh_fromChanging(value);
					this.SendPropertyChanging();
					this._sh_from = value;
					this.SendPropertyChanged("sh_from");
					this.Onsh_fromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh_to", DbType="Time NOT NULL")]
		public System.TimeSpan sh_to
		{
			get
			{
				return this._sh_to;
			}
			set
			{
				if ((this._sh_to != value))
				{
					this.Onsh_toChanging(value);
					this.SendPropertyChanging();
					this._sh_to = value;
					this.SendPropertyChanged("sh_to");
					this.Onsh_toChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="shift_timing", Storage="_timings", ThisKey="sh_id", OtherKey="t_shift")]
		public EntitySet<timing> timings
		{
			get
			{
				return this._timings;
			}
			set
			{
				this._timings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_timings(timing entity)
		{
			this.SendPropertyChanging();
			entity.shift = this;
		}
		
		private void detach_timings(timing entity)
		{
			this.SendPropertyChanging();
			entity.shift = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.levels")]
	public partial class level : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _l_id;
		
		private string _l_name;

        private EntitySet<clase> _classes;
		
		private EntitySet<timing> _timings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onl_idChanging(int value);
    partial void Onl_idChanged();
    partial void Onl_nameChanging(string value);
    partial void Onl_nameChanged();
    #endregion
		
		public level()
		{
            this._classes = new EntitySet<clase>(new Action<clase>(this.attach_classes), new Action<clase>(this.detach_classes));
			this._timings = new EntitySet<timing>(new Action<timing>(this.attach_timings), new Action<timing>(this.detach_timings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int l_id
		{
			get
			{
				return this._l_id;
			}
			set
			{
				if ((this._l_id != value))
				{
					this.Onl_idChanging(value);
					this.SendPropertyChanging();
					this._l_id = value;
					this.SendPropertyChanged("l_id");
					this.Onl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string l_name
		{
			get
			{
				return this._l_name;
			}
			set
			{
				if ((this._l_name != value))
				{
					this.Onl_nameChanging(value);
					this.SendPropertyChanging();
					this._l_name = value;
					this.SendPropertyChanged("l_name");
					this.Onl_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="level_class", Storage="_classes", ThisKey="l_id", OtherKey="cls_levelID")]
        public EntitySet<clase> classes
		{
			get
			{
				return this._classes;
			}
			set
			{
				this._classes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="level_timing", Storage="_timings", ThisKey="l_id", OtherKey="t_levelID")]
		public EntitySet<timing> timings
		{
			get
			{
				return this._timings;
			}
			set
			{
				this._timings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

        private void attach_classes(clase entity)
		{
			this.SendPropertyChanging();
			entity.level = this;
		}

        private void detach_classes(clase entity)
		{
			this.SendPropertyChanging();
			entity.level = null;
		}
		
		private void attach_timings(timing entity)
		{
			this.SendPropertyChanging();
			entity.level = this;
		}
		
		private void detach_timings(timing entity)
		{
			this.SendPropertyChanging();
			entity.level = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.classes")]
	public partial class clase : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cls_id;
		
		private string _cls_name;
		
		private byte _cls_status;
		
		private System.Nullable<int> _cls_levelID;
		
		private EntitySet<subject> _subjects;
		
		private EntityRef<level> _level;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncls_idChanging(int value);
    partial void Oncls_idChanged();
    partial void Oncls_nameChanging(string value);
    partial void Oncls_nameChanged();
    partial void Oncls_statusChanging(byte value);
    partial void Oncls_statusChanged();
    partial void Oncls_levelIDChanging(System.Nullable<int> value);
    partial void Oncls_levelIDChanged();
    #endregion

    public clase()
		{
			this._subjects = new EntitySet<subject>(new Action<subject>(this.attach_subjects), new Action<subject>(this.detach_subjects));
			this._level = default(EntityRef<level>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cls_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cls_id
		{
			get
			{
				return this._cls_id;
			}
			set
			{
				if ((this._cls_id != value))
				{
					this.Oncls_idChanging(value);
					this.SendPropertyChanging();
					this._cls_id = value;
					this.SendPropertyChanged("cls_id");
					this.Oncls_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cls_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cls_name
		{
			get
			{
				return this._cls_name;
			}
			set
			{
				if ((this._cls_name != value))
				{
					this.Oncls_nameChanging(value);
					this.SendPropertyChanging();
					this._cls_name = value;
					this.SendPropertyChanged("cls_name");
					this.Oncls_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cls_status", DbType="TinyInt NOT NULL")]
		public byte cls_status
		{
			get
			{
				return this._cls_status;
			}
			set
			{
				if ((this._cls_status != value))
				{
					this.Oncls_statusChanging(value);
					this.SendPropertyChanging();
					this._cls_status = value;
					this.SendPropertyChanged("cls_status");
					this.Oncls_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cls_levelID", DbType="Int")]
		public System.Nullable<int> cls_levelID
		{
			get
			{
				return this._cls_levelID;
			}
			set
			{
				if ((this._cls_levelID != value))
				{
					if (this._level.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncls_levelIDChanging(value);
					this.SendPropertyChanging();
					this._cls_levelID = value;
					this.SendPropertyChanged("cls_levelID");
					this.Oncls_levelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="class_subject", Storage="_subjects", ThisKey="cls_id", OtherKey="sub_classID")]
		public EntitySet<subject> subjects
		{
			get
			{
				return this._subjects;
			}
			set
			{
				this._subjects.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="level_class", Storage="_level", ThisKey="cls_levelID", OtherKey="l_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public level level
		{
			get
			{
				return this._level.Entity;
			}
			set
			{
				level previousValue = this._level.Entity;
				if (((previousValue != value) 
							|| (this._level.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._level.Entity = null;
						previousValue.classes.Remove(this);
					}
					this._level.Entity = value;
					if ((value != null))
					{
						value.classes.Add(this);
						this._cls_levelID = value.l_id;
					}
					else
					{
						this._cls_levelID = default(Nullable<int>);
					}
					this.SendPropertyChanged("level");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_subjects(subject entity)
		{
			this.SendPropertyChanging();
			entity.@class = this;
		}
		
		private void detach_subjects(subject entity)
		{
			this.SendPropertyChanging();
			entity.@class = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.timings")]
	public partial class timing : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _t_id;
		
		private string _t_name;
		
		private int _t_shift;
		
		private System.TimeSpan _t_fromTime;
		
		private System.TimeSpan _t_toTime;
		
		private string _t_dayName;
		
		private int _t_levelID;
		
		private EntityRef<shift> _shift;
		
		private EntityRef<level> _level;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ont_idChanging(int value);
    partial void Ont_idChanged();
    partial void Ont_nameChanging(string value);
    partial void Ont_nameChanged();
    partial void Ont_shiftChanging(int value);
    partial void Ont_shiftChanged();
    partial void Ont_fromTimeChanging(System.TimeSpan value);
    partial void Ont_fromTimeChanged();
    partial void Ont_toTimeChanging(System.TimeSpan value);
    partial void Ont_toTimeChanged();
    partial void Ont_dayNameChanging(string value);
    partial void Ont_dayNameChanged();
    partial void Ont_levelIDChanging(int value);
    partial void Ont_levelIDChanged();
    #endregion
		
		public timing()
		{
			this._shift = default(EntityRef<shift>);
			this._level = default(EntityRef<level>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int t_id
		{
			get
			{
				return this._t_id;
			}
			set
			{
				if ((this._t_id != value))
				{
					this.Ont_idChanging(value);
					this.SendPropertyChanging();
					this._t_id = value;
					this.SendPropertyChanged("t_id");
					this.Ont_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string t_name
		{
			get
			{
				return this._t_name;
			}
			set
			{
				if ((this._t_name != value))
				{
					this.Ont_nameChanging(value);
					this.SendPropertyChanging();
					this._t_name = value;
					this.SendPropertyChanged("t_name");
					this.Ont_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_shift", DbType="Int NOT NULL")]
		public int t_shift
		{
			get
			{
				return this._t_shift;
			}
			set
			{
				if ((this._t_shift != value))
				{
					if (this._shift.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ont_shiftChanging(value);
					this.SendPropertyChanging();
					this._t_shift = value;
					this.SendPropertyChanged("t_shift");
					this.Ont_shiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_fromTime", DbType="Time NOT NULL")]
		public System.TimeSpan t_fromTime
		{
			get
			{
				return this._t_fromTime;
			}
			set
			{
				if ((this._t_fromTime != value))
				{
					this.Ont_fromTimeChanging(value);
					this.SendPropertyChanging();
					this._t_fromTime = value;
					this.SendPropertyChanged("t_fromTime");
					this.Ont_fromTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_toTime", DbType="Time NOT NULL")]
		public System.TimeSpan t_toTime
		{
			get
			{
				return this._t_toTime;
			}
			set
			{
				if ((this._t_toTime != value))
				{
					this.Ont_toTimeChanging(value);
					this.SendPropertyChanging();
					this._t_toTime = value;
					this.SendPropertyChanged("t_toTime");
					this.Ont_toTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_dayName", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string t_dayName
		{
			get
			{
				return this._t_dayName;
			}
			set
			{
				if ((this._t_dayName != value))
				{
					this.Ont_dayNameChanging(value);
					this.SendPropertyChanging();
					this._t_dayName = value;
					this.SendPropertyChanged("t_dayName");
					this.Ont_dayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_levelID", DbType="Int NOT NULL")]
		public int t_levelID
		{
			get
			{
				return this._t_levelID;
			}
			set
			{
				if ((this._t_levelID != value))
				{
					if (this._level.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ont_levelIDChanging(value);
					this.SendPropertyChanging();
					this._t_levelID = value;
					this.SendPropertyChanged("t_levelID");
					this.Ont_levelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="shift_timing", Storage="_shift", ThisKey="t_shift", OtherKey="sh_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public shift shift
		{
			get
			{
				return this._shift.Entity;
			}
			set
			{
				shift previousValue = this._shift.Entity;
				if (((previousValue != value) 
							|| (this._shift.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._shift.Entity = null;
						previousValue.timings.Remove(this);
					}
					this._shift.Entity = value;
					if ((value != null))
					{
						value.timings.Add(this);
						this._t_shift = value.sh_id;
					}
					else
					{
						this._t_shift = default(int);
					}
					this.SendPropertyChanged("shift");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="level_timing", Storage="_level", ThisKey="t_levelID", OtherKey="l_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public level level
		{
			get
			{
				return this._level.Entity;
			}
			set
			{
				level previousValue = this._level.Entity;
				if (((previousValue != value) 
							|| (this._level.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._level.Entity = null;
						previousValue.timings.Remove(this);
					}
					this._level.Entity = value;
					if ((value != null))
					{
						value.timings.Add(this);
						this._t_levelID = value.l_id;
					}
					else
					{
						this._t_levelID = default(int);
					}
					this.SendPropertyChanged("level");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class st_getRolesResult
	{
		
		private int _ID;
		
		private string _Role;
		
		private string _Status;
		
		public st_getRolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class st_searchRolesResult
	{
		
		private int _ID;
		
		private string _Role;
		
		private string _Status;
		
		public st_searchRolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class st_getStaffDetailsResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Password;
		
		private string _Username;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Role;
		
		private int _RoleID;
		
		private string _Status;
		
		public st_getStaffDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this._Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(15)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this._Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class st_getSectionsResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Status;
		
		public st_getSectionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class st_getSubjectsResult
	{
		
		private int _ID;
		
		private string _Subjects;
		
		private int _ClassID;
		
		private string _Class;
		
		public st_getSubjectsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subjects", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Subjects
		{
			get
			{
				return this._Subjects;
			}
			set
			{
				if ((this._Subjects != value))
				{
					this._Subjects = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL")]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this._ClassID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this._Class = value;
				}
			}
		}
	}
	
	public partial class st_getShiftsResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _From;
		
		private string _To;
		
		private byte _Number;
		
		public st_getShiftsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[From]", Storage="_From", DbType="NVarChar(4000)")]
		public string From
		{
			get
			{
				return this._From;
			}
			set
			{
				if ((this._From != value))
				{
					this._From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[To]", Storage="_To", DbType="NVarChar(4000)")]
		public string To
		{
			get
			{
				return this._To;
			}
			set
			{
				if ((this._To != value))
				{
					this._To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="TinyInt NOT NULL")]
		public byte Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
	}
	
	public partial class st_gethousseResult
	{
		
		private int _ID;
		
		private string _House;
		
		private string _Status;
		
		public st_gethousseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_House", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string House
		{
			get
			{
				return this._House;
			}
			set
			{
				if ((this._House != value))
				{
					this._House = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class st_getStaffLoginDetailsResult
	{
		
		private int _Staff_ID;
		
		private string _Username;
		
		private string _Password;
		
		private string _Name;
		
		private string _Role;
		
		public st_getStaffLoginDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Staff ID]", Storage="_Staff_ID", DbType="Int NOT NULL")]
		public int Staff_ID
		{
			get
			{
				return this._Staff_ID;
			}
			set
			{
				if ((this._Staff_ID != value))
				{
					this._Staff_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
	}
	
	public partial class st_getlevelResult
	{
		
		private int _ID;
		
		private string _LevelName;
		
		public st_getlevelResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LevelName
		{
			get
			{
				return this._LevelName;
			}
			set
			{
				if ((this._LevelName != value))
				{
					this._LevelName = value;
				}
			}
		}
	}
	
	public partial class st_getClassesResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Status;
		
		private string _Level;
		
		private int _LevelID;
		
		public st_getClassesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelID", DbType="Int NOT NULL")]
		public int LevelID
		{
			get
			{
				return this._LevelID;
			}
			set
			{
				if ((this._LevelID != value))
				{
					this._LevelID = value;
				}
			}
		}
	}
	
	public partial class st_getTimingsResult
	{
		
		private int _ID;
		
		private string _TimingName;
		
		private System.TimeSpan _From;
		
		private System.TimeSpan _To;
		
		private int _ShiftID;
		
		private string _ShiftName;
		
		private string _Day;
		
		private int _LevelID;
		
		private string _Level;
		
		public st_getTimingsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimingName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TimingName
		{
			get
			{
				return this._TimingName;
			}
			set
			{
				if ((this._TimingName != value))
				{
					this._TimingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[From]", Storage="_From", DbType="Time NOT NULL")]
		public System.TimeSpan From
		{
			get
			{
				return this._From;
			}
			set
			{
				if ((this._From != value))
				{
					this._From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[To]", Storage="_To", DbType="Time NOT NULL")]
		public System.TimeSpan To
		{
			get
			{
				return this._To;
			}
			set
			{
				if ((this._To != value))
				{
					this._To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftID", DbType="Int NOT NULL")]
		public int ShiftID
		{
			get
			{
				return this._ShiftID;
			}
			set
			{
				if ((this._ShiftID != value))
				{
					this._ShiftID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ShiftName
		{
			get
			{
				return this._ShiftName;
			}
			set
			{
				if ((this._ShiftName != value))
				{
					this._ShiftName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this._Day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelID", DbType="Int NOT NULL")]
		public int LevelID
		{
			get
			{
				return this._LevelID;
			}
			set
			{
				if ((this._LevelID != value))
				{
					this._LevelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
